//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IMultiService")]
public interface IMultiService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMultiService/GetData", ReplyAction="http://tempuri.org/IMultiService/GetDataResponse")]
    int GetData(int a, int b);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMultiService/GetData", ReplyAction="http://tempuri.org/IMultiService/GetDataResponse")]
    System.Threading.Tasks.Task<int> GetDataAsync(int a, int b);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IMultiServiceChannel : IMultiService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class MultiServiceClient : System.ServiceModel.ClientBase<IMultiService>, IMultiService
{
    
    public MultiServiceClient()
    {
    }
    
    public MultiServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public MultiServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MultiServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public MultiServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public int GetData(int a, int b)
    {
        return base.Channel.GetData(a, b);
    }
    
    public System.Threading.Tasks.Task<int> GetDataAsync(int a, int b)
    {
        return base.Channel.GetDataAsync(a, b);
    }
}
